// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEBuoDQ8_8Q2oaFLiUVprPaGC2N_bO3E',
    appId: '1:813884586804:web:03d5d987d60ca3ea178361',
    messagingSenderId: '813884586804',
    projectId: 'socialappamit',
    authDomain: 'socialappamit.firebaseapp.com',
    storageBucket: 'socialappamit.appspot.com',
    measurementId: 'G-CZZ70DFVMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxS60tMk0CMXViAC7ccvm992S9h8VJ5E',
    appId: '1:813884586804:android:9f1b890e86acf6cc178361',
    messagingSenderId: '813884586804',
    projectId: 'socialappamit',
    storageBucket: 'socialappamit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkNr55ALpCtkd572cOThB6Pt8EeIMEmwY',
    appId: '1:813884586804:ios:86879145bbd2bf08178361',
    messagingSenderId: '813884586804',
    projectId: 'socialappamit',
    storageBucket: 'socialappamit.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkNr55ALpCtkd572cOThB6Pt8EeIMEmwY',
    appId: '1:813884586804:ios:46d0b1b50b0bc2b1178361',
    messagingSenderId: '813884586804',
    projectId: 'socialappamit',
    storageBucket: 'socialappamit.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
